[project]
name = "hello-sky"
version = "0.1.0"
description = "hello-sky"
readme = "README.md"
requires-python = ">=3.11.8"
dependencies = [
    "ray[serve]>=2.44.1",
    "skypilot[aws,kubernetes]>=0.8.1",
]
